# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"twoNumberSum": "00_core.ipynb",
         "twoNumberSumHarshTable": "00_core.ipynb",
         "twoNumberSumPoints": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://lyuhaitao.github.io/lyuAlgorithm/"

git_url = "https://github.com/lyuhaitao/lyuAlgorithm/tree/master/"

def custom_doc_links(name): return None
